# Generated by Django 5.1.5 on 2025-01-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Unnamed Car', max_length=256),
        ),
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
